# .readthedocs.yaml
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.9"

python:
  install:
    - requirements: docs/requirements.txt  # 如果你有requirements.txt

sphinx:
  configuration: docs/conf.py  # 你的Sphinx配置文件路径
